// ─── Predefined suggestion lists ────────────────────────────────────────────
export const COMMON_MEDICAL_CONDITIONS = [
  "Hypertension",
  "Diabetes",
  "Asthma",
  "Heart Disease",
  "Arthritis",
  "Depression",
  "Anxiety",
  "Epilepsy",
  "Sickle Cell Disease",
  "HIV/AIDS",
  "Cancer",
  "Kidney Disease",
  "Thyroid Disorder",
  "COPD",
  "Hepatitis",
  "Stroke",
  "Malaria",
  "Tuberculosis",
  "Ulcer",
  "Migraine",
];

export const COMMON_ALLERGIES = [
  "Penicillin",
  "Sulfa Drugs",
  "Aspirin",
  "Ibuprofen",
  "Latex",
  "Peanuts",
  "Shellfish",
  "Eggs",
  "Dust",
  "Pollen",
  "Pet Dander",
  "Mold",
  "Bee Stings",
  "Soy",
  "Milk",
  "Gluten",
  "Codeine",
  "Morphine",
  "Tree Nuts",
  "Fish",
];
